version: "3"
services:
  nginx:
    image: nginx:stable-alpine

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - node-app

  node-app:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000

    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vaibhav
      - MONGO_INITDB_ROOT_PASSWORD=kalavathi
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
